CREATE TABLE IF NOT EXISTS players (
    owner_id BIGINT PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(32) NOT NULL,
    map_id INT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    explored INT[] NOT NULL DEFAULT '{0}'::INT[]
);

CREATE TABLE IF NOT EXISTS blacklist (
    user_id BIGINT PRIMARY KEY UNIQUE NOT NULL,
    reason VARCHAR(255) NOT NULL
);
